include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Const 관련 규칙 (성능 최적화)
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true

    # 코드 품질 규칙
    avoid_print: true  # print 대신 debugPrint 사용
    prefer_final_locals: true  # 변경되지 않는 변수는 final로
    unnecessary_null_checks: true

    # 가독성 향상
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore
