name: gong_mu_talk
description: "공무원을 위한 종합 자산 관리 및 커뮤니티 플랫폼"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.12
  dio: ^5.8.0+1
  equatable: ^2.0.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_crashlytics: ^4.3.10
  firebase_analytics: ^11.3.4
  firebase_performance: ^0.10.0+8
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  get_it: ^8.1.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  share_plus: ^7.2.1
  app_links: ^6.3.4
  logger: ^2.6.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  shorebird_code_push: ^1.0.6
  skeletonizer: ^2.1.0+1
  stream_transform: ^2.1.1
  rive: ^0.13.3
  image_picker: ^1.0.7
  file_picker: ^10.3.3
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.4
  url_launcher: ^6.2.1
  collection: ^1.18.0
  package_info_plus: ^8.0.2
  image: ^4.2.0
  flutter_image_compress: ^2.4.0
  path: ^1.9.0
  fl_chart: ^0.66.0
  sentry_flutter: ^8.14.0
  dartz: ^0.10.1  # Functional programming (Either, Option)
  tuple: ^2.0.2  # Tuple types for cleaner data structures

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  test: ^1.25.4
  very_good_analysis: ^6.0.0  # Enhanced linting rules

flutter:
  uses-material-design: true
  assets:
    - assets/data/salary_tables.json
    - assets/logo/
    - assets/images/
    - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo/gong_mu_talk_logo.png
  adaptive_icon_background: "#181C27"
  adaptive_icon_foreground: assets/logo/gong_mu_talk_logo.png
  adaptive_icon_foreground_inset: 22
  min_sdk_android: 21
