name: gong_mu_talk
description: "공무원을 위한 종합 자산 관리 및 커뮤니티 플랫폼"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.5
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.2
  firebase_crashlytics: ^5.0.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  get_it: ^8.1.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  kakao_flutter_sdk_user: ^1.9.7+3
  logger: ^2.6.1
  lottie: ^3.3.1
  path_provider: ^2.1.5
  retrofit: ^4.7.0
  shorebird_code_push: ^1.0.6
  skeletonizer: ^2.1.0+1
  stream_transform: ^2.1.1
  bootpay: ^4.9.96

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0
  injectable_generator: ^2.8.1
  go_router_builder: ^4.0.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/salary_tables.json
