import 'lounge_model.dart';

/// 라운지 설정 - 기본 라운지 목록 정의
/// 
/// 파일 분리 이유: CLAUDE.md 파일 크기 원칙 준수
/// - 기존 lounge.dart (994줄, Red Zone) → 분리
/// - lounge_model.dart (~300줄, Green Zone)
/// - lounge_definitions.dart (~450줄, Green Zone)
class LoungeDefinitions {
  LoungeDefinitions._();

  static const List<Lounge> defaultLounges = [
    // ========================================
    // 0. 전체 라운지
    // ========================================
    Lounge(
      id: 'all',
      name: '전체',
      emoji: '🏛️',
      shortName: '전체',
      type: LoungeType.all,
      accessType: LoungeAccessType.public,
      requiredCareerIds: [],
      memberCount: 1000000,
      description: '모든 공무원이 참여하는 라운지',
      order: 0,
    ),

    // ========================================
    // 1. 교육공무원 - 교사
    // ========================================
    Lounge(
      id: 'teacher',
      name: '교사',
      emoji: '📚',
      shortName: '교사',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'elementary_teacher',
        'kindergarten_teacher',
        'special_education_teacher',
        'secondary_math_teacher',
        'secondary_korean_teacher',
        'secondary_english_teacher',
        'secondary_science_teacher',
        'secondary_social_teacher',
        'secondary_arts_teacher',
        'counselor_teacher',
        'health_teacher',
        'librarian_teacher',
        'nutrition_teacher',
      ],
      memberCount: 430000,
      description: '모든 교사가 참여하는 라운지',
      order: 1,
    ),

    Lounge(
      id: 'elementary_teacher',
      name: '초등교사',
      emoji: '🏫',
      shortName: '초등교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['elementary_teacher'],
      parentLoungeId: 'teacher',
      memberCount: 180000,
      description: '초등교사 전용 라운지',
      order: 11,
    ),

    Lounge(
      id: 'kindergarten_teacher',
      name: '유치원교사',
      emoji: '👶',
      shortName: '유치원교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['kindergarten_teacher'],
      parentLoungeId: 'teacher',
      memberCount: 5000,
      description: '유치원교사 전용 라운지',
      order: 12,
    ),

    Lounge(
      id: 'special_education_teacher',
      name: '특수교육교사',
      emoji: '🤝',
      shortName: '특수교육교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['special_education_teacher'],
      parentLoungeId: 'teacher',
      memberCount: 4000,
      description: '특수교육교사 전용 라운지',
      order: 13,
    ),

    Lounge(
      id: 'secondary_teacher',
      name: '중등교사',
      emoji: '🎓',
      shortName: '중등교사',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'secondary_math_teacher',
        'secondary_korean_teacher',
        'secondary_english_teacher',
        'secondary_science_teacher',
        'secondary_social_teacher',
        'secondary_arts_teacher',
      ],
      parentLoungeId: 'teacher',
      memberCount: 200000,
      description: '중등교사 전용 라운지',
      order: 14,
    ),

    Lounge(
      id: 'secondary_math_teacher',
      name: '중등수학교사',
      emoji: '📐',
      shortName: '중등수학교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['secondary_math_teacher'],
      parentLoungeId: 'secondary_teacher',
      memberCount: 30000,
      description: '중등 수학교사 전용 라운지',
      order: 141,
    ),

    Lounge(
      id: 'secondary_korean_teacher',
      name: '중등국어교사',
      emoji: '📖',
      shortName: '중등국어교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['secondary_korean_teacher'],
      parentLoungeId: 'secondary_teacher',
      memberCount: 30000,
      description: '중등 국어교사 전용 라운지',
      order: 142,
    ),

    Lounge(
      id: 'secondary_english_teacher',
      name: '중등영어교사',
      emoji: '🌍',
      shortName: '중등영어교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['secondary_english_teacher'],
      parentLoungeId: 'secondary_teacher',
      memberCount: 25000,
      description: '중등 영어교사 전용 라운지',
      order: 143,
    ),

    Lounge(
      id: 'secondary_science_teacher',
      name: '중등과학교사',
      emoji: '🔬',
      shortName: '중등과학교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['secondary_science_teacher'],
      parentLoungeId: 'secondary_teacher',
      memberCount: 30000,
      description: '중등 과학교사 전용 라운지',
      order: 144,
    ),

    Lounge(
      id: 'secondary_social_teacher',
      name: '중등사회교사',
      emoji: '🌏',
      shortName: '중등사회교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['secondary_social_teacher'],
      parentLoungeId: 'secondary_teacher',
      memberCount: 25000,
      description: '중등 사회교사 전용 라운지',
      order: 145,
    ),

    Lounge(
      id: 'secondary_arts_teacher',
      name: '중등예체능교사',
      emoji: '🎨',
      shortName: '중등예체능교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['secondary_arts_teacher'],
      parentLoungeId: 'secondary_teacher',
      memberCount: 60000,
      description: '중등 예체능교사 전용 라운지',
      order: 146,
    ),

    Lounge(
      id: 'non_subject_teacher',
      name: '비교과교사',
      emoji: '💼',
      shortName: '비교과교사',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'counselor_teacher',
        'health_teacher',
        'librarian_teacher',
        'nutrition_teacher',
      ],
      parentLoungeId: 'teacher',
      memberCount: 15000,
      description: '상담·보건·사서·영양 교사 라운지',
      order: 15,
    ),

    // ========================================
    // 1-1. 교육행정직 (신규)
    // ========================================
    Lounge(
      id: 'education_admin',
      name: '교육행정직',
      emoji: '📋',
      shortName: '교육행정직',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'education_admin_9th_national',
        'education_admin_7th_national',
        'education_admin_9th_local',
        'education_admin_7th_local',
      ],
      memberCount: 18000,
      description: '교육행정직 공무원 라운지',
      order: 16,
    ),

    Lounge(
      id: 'national_education_admin',
      name: '국가 교육행정직',
      emoji: '🏛️',
      shortName: '국가 교육행정',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'education_admin_9th_national',
        'education_admin_7th_national',
      ],
      parentLoungeId: 'education_admin',
      memberCount: 5000,
      description: '국가 교육행정직 공무원 라운지',
      order: 161,
    ),

    Lounge(
      id: 'education_admin_9th_national',
      name: '9급 국가 교육행정직',
      emoji: '📋',
      shortName: '9급 국가교육행정',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['education_admin_9th_national'],
      parentLoungeId: 'national_education_admin',
      memberCount: 2500,
      description: '9급 국가 교육행정직 공무원 라운지',
      order: 1611,
    ),

    Lounge(
      id: 'education_admin_7th_national',
      name: '7급 국가 교육행정직',
      emoji: '📊',
      shortName: '7급 국가교육행정',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['education_admin_7th_national'],
      parentLoungeId: 'national_education_admin',
      memberCount: 2500,
      description: '7급 국가 교육행정직 공무원 라운지',
      order: 1612,
    ),

    Lounge(
      id: 'local_education_admin',
      name: '지방 교육행정직',
      emoji: '🏢',
      shortName: '지방 교육행정',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'education_admin_9th_local',
        'education_admin_7th_local',
      ],
      parentLoungeId: 'education_admin',
      memberCount: 13000,
      description: '지방 교육행정직 공무원 라운지',
      order: 162,
    ),

    Lounge(
      id: 'education_admin_9th_local',
      name: '9급 지방 교육행정직',
      emoji: '📋',
      shortName: '9급 지방교육행정',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['education_admin_9th_local'],
      parentLoungeId: 'local_education_admin',
      memberCount: 8000,
      description: '9급 지방 교육행정직 공무원 라운지',
      order: 1621,
    ),

    Lounge(
      id: 'education_admin_7th_local',
      name: '7급 지방 교육행정직',
      emoji: '📊',
      shortName: '7급 지방교육행정',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['education_admin_7th_local'],
      parentLoungeId: 'local_education_admin',
      memberCount: 5000,
      description: '7급 지방 교육행정직 공무원 라운지',
      order: 1622,
    ),

    // ========================================
    // 2. 행정직
    // ========================================
    Lounge(
      id: 'admin',
      name: '행정직',
      emoji: '🗂️',
      shortName: '행정직',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'admin_9th_national',
        'admin_7th_national',
        'admin_5th_national',
        'admin_9th_local',
        'admin_7th_local',
        'admin_5th_local',
        'tax_officer',
        'customs_officer',
        'job_counselor',
        'statistics_officer',
        'librarian',
        'auditor',
        'security_officer',
      ],
      memberCount: 280000,
      description: '행정직 공무원 라운지',
      order: 2,
    ),

    Lounge(
      id: 'national_admin',
      name: '국가행정직',
      emoji: '🏛️',
      shortName: '국가행정직',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'admin_9th_national',
        'admin_7th_national',
        'admin_5th_national',
      ],
      parentLoungeId: 'admin',
      memberCount: 80000,
      description: '국가직 행정공무원 라운지',
      order: 21,
    ),

    Lounge(
      id: 'admin_9th_national',
      name: '9급 국가행정직',
      emoji: '📋',
      shortName: '9급 국가행정직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['admin_9th_national'],
      parentLoungeId: 'national_admin',
      memberCount: 30000,
      description: '9급 국가직 행정공무원 라운지',
      order: 211,
    ),

    Lounge(
      id: 'admin_7th_national',
      name: '7급 국가행정직',
      emoji: '📊',
      shortName: '7급 국가행정직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['admin_7th_national'],
      parentLoungeId: 'national_admin',
      memberCount: 30000,
      description: '7급 국가직 행정공무원 라운지',
      order: 212,
    ),

    Lounge(
      id: 'admin_5th_national',
      name: '5급 국가행정직',
      emoji: '💼',
      shortName: '5급 국가행정직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['admin_5th_national'],
      parentLoungeId: 'national_admin',
      memberCount: 20000,
      description: '5급 국가직 행정공무원 라운지',
      order: 213,
    ),

    Lounge(
      id: 'local_admin',
      name: '지방행정직',
      emoji: '🏢',
      shortName: '지방행정직',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'admin_9th_local',
        'admin_7th_local',
        'admin_5th_local',
      ],
      parentLoungeId: 'admin',
      memberCount: 150000,
      description: '지방직 행정공무원 라운지',
      order: 22,
    ),

    Lounge(
      id: 'admin_9th_local',
      name: '9급 지방행정직',
      emoji: '📋',
      shortName: '9급 지방행정직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['admin_9th_local'],
      parentLoungeId: 'local_admin',
      memberCount: 80000,
      description: '9급 지방직 행정공무원 라운지',
      order: 221,
    ),

    Lounge(
      id: 'admin_7th_local',
      name: '7급 지방행정직',
      emoji: '📊',
      shortName: '7급 지방행정직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['admin_7th_local'],
      parentLoungeId: 'local_admin',
      memberCount: 50000,
      description: '7급 지방직 행정공무원 라운지',
      order: 222,
    ),

    Lounge(
      id: 'admin_5th_local',
      name: '5급 지방행정직',
      emoji: '💼',
      shortName: '5급 지방행정직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['admin_5th_local'],
      parentLoungeId: 'local_admin',
      memberCount: 20000,
      description: '5급 지방직 행정공무원 라운지',
      order: 223,
    ),

    Lounge(
      id: 'tax_customs',
      name: '세무·관세직',
      emoji: '💰',
      shortName: '세무·관세직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['tax_officer', 'customs_officer'],
      parentLoungeId: 'admin',
      memberCount: 25000,
      description: '세무직 및 관세직 공무원 라운지',
      order: 23,
    ),

    Lounge(
      id: 'specialized_admin',
      name: '전문행정직',
      emoji: '📋',
      shortName: '전문행정직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'job_counselor',
        'statistics_officer',
        'librarian',
        'auditor',
        'security_officer',
      ],
      parentLoungeId: 'admin',
      memberCount: 30000,
      description: '고용노동·통계·사서·감사·방호직 라운지',
      order: 24,
    ),

    // ========================================
    // 3. 치안/안전직
    // ========================================
    Lounge(
      id: 'police',
      name: '경찰관',
      emoji: '👮‍♂️',
      shortName: '경찰관',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['police'],
      memberCount: 120000,
      description: '경찰관 전용 라운지',
      order: 3,
    ),

    Lounge(
      id: 'firefighter',
      name: '소방관',
      emoji: '👨‍🚒',
      shortName: '소방관',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['firefighter'],
      memberCount: 50000,
      description: '소방관 전용 라운지',
      order: 4,
    ),

    Lounge(
      id: 'coast_guard',
      name: '해양경찰',
      emoji: '🌊',
      shortName: '해양경찰',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['coast_guard'],
      memberCount: 10000,
      description: '해양경찰 전용 라운지',
      order: 41,
    ),

    // ========================================
    // 4. 보건복지직
    // ========================================
    Lounge(
      id: 'health_welfare',
      name: '보건복지직',
      emoji: '🏥',
      shortName: '보건복지직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'public_health_officer',
        'medical_technician',
        'nurse',
        'medical_officer',
        'pharmacist',
        'food_sanitation',
        'social_worker',
      ],
      memberCount: 80000,
      description: '보건·의료·간호·약무·복지직 라운지',
      order: 5,
    ),

    // ========================================
    // 5. 공안직
    // ========================================
    Lounge(
      id: 'public_security',
      name: '공안직',
      emoji: '⚖️',
      shortName: '공안직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'correction_officer',
        'probation_officer',
        'prosecution_officer',
        'drug_investigation_officer',
        'immigration_officer',
        'railroad_police',
        'security_guard',
      ],
      memberCount: 50000,
      description: '교정·검찰·마약수사·출입국관리직 라운지',
      order: 6,
    ),

    // ========================================
    // 6. 군인
    // ========================================
    Lounge(
      id: 'military',
      name: '군인',
      emoji: '🎖️',
      shortName: '군인',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['army', 'navy', 'air_force', 'military_civilian'],
      memberCount: 80000,
      description: '군인 전용 라운지',
      order: 7,
    ),

    Lounge(
      id: 'army',
      name: '육군',
      emoji: '🪖',
      shortName: '육군',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['army'],
      parentLoungeId: 'military',
      memberCount: 50000,
      description: '육군 전용 라운지',
      order: 71,
    ),

    Lounge(
      id: 'navy',
      name: '해군',
      emoji: '⚓',
      shortName: '해군',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['navy'],
      parentLoungeId: 'military',
      memberCount: 15000,
      description: '해군 전용 라운지',
      order: 72,
    ),

    Lounge(
      id: 'air_force',
      name: '공군',
      emoji: '✈️',
      shortName: '공군',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['air_force'],
      parentLoungeId: 'military',
      memberCount: 15000,
      description: '공군 전용 라운지',
      order: 73,
    ),

    Lounge(
      id: 'military_civilian',
      name: '군무원',
      emoji: '🎖️',
      shortName: '군무원',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['military_civilian'],
      parentLoungeId: 'military',
      memberCount: 30000,
      description: '군무원 전용 라운지',
      order: 74,
    ),

    // ========================================
    // 7. 기술직
    // ========================================
    Lounge(
      id: 'technical',
      name: '기술직',
      emoji: '⚙️',
      shortName: '기술직',
      type: LoungeType.category,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'mechanical_engineer',
        'electrical_engineer',
        'electronics_engineer',
        'chemical_engineer',
        'shipbuilding_engineer',
        'nuclear_engineer',
        'metal_engineer',
        'textile_engineer',
        'civil_engineer',
        'architect',
        'landscape_architect',
        'traffic_engineer',
        'cadastral_officer',
        'designer',
        'environmental_officer',
        'agriculture_officer',
        'plant_quarantine',
        'livestock_officer',
        'forestry_officer',
        'marine_officer',
        'fisheries_officer',
        'ship_officer',
        'veterinarian',
        'agricultural_extension',
        'computer_officer',
        'broadcasting_communication',
        'facility_management',
        'sanitation_worker',
        'cook',
      ],
      memberCount: 300000,
      description: '모든 기술직 공무원 라운지',
      order: 8,
    ),

    Lounge(
      id: 'industrial_engineer',
      name: '공업직',
      emoji: '⚙️',
      shortName: '공업직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'mechanical_engineer',
        'electrical_engineer',
        'electronics_engineer',
        'chemical_engineer',
        'shipbuilding_engineer',
        'nuclear_engineer',
        'metal_engineer',
        'textile_engineer',
      ],
      parentLoungeId: 'technical',
      memberCount: 50000,
      description: '기계·전기·전자·화공직 등 공업 기술직',
      order: 81,
    ),

    Lounge(
      id: 'facilities_environment',
      name: '시설환경직',
      emoji: '🏗️',
      shortName: '시설환경직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'civil_engineer',
        'architect',
        'landscape_architect',
        'traffic_engineer',
        'cadastral_officer',
        'designer',
        'environmental_officer',
      ],
      parentLoungeId: 'technical',
      memberCount: 47000,
      description: '토목·건축·환경직 등 시설환경 기술직',
      order: 82,
    ),

    Lounge(
      id: 'agriculture_forestry_fisheries',
      name: '농림수산직',
      emoji: '🌾',
      shortName: '농림수산직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'agriculture_officer',
        'plant_quarantine',
        'livestock_officer',
        'forestry_officer',
        'marine_officer',
        'fisheries_officer',
        'ship_officer',
        'veterinarian',
        'agricultural_extension',
      ],
      parentLoungeId: 'technical',
      memberCount: 70000,
      description: '농업·수산·축산·수의직 등',
      order: 83,
    ),

    Lounge(
      id: 'it_communications',
      name: 'IT통신직',
      emoji: '💻',
      shortName: 'IT통신직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['computer_officer', 'broadcasting_communication'],
      parentLoungeId: 'technical',
      memberCount: 20000,
      description: '전산·방송통신직 라운지',
      order: 84,
    ),

    Lounge(
      id: 'management_operations',
      name: '관리운영직',
      emoji: '🏢',
      shortName: '관리운영직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['facility_management', 'sanitation_worker', 'cook'],
      parentLoungeId: 'technical',
      memberCount: 35000,
      description: '시설관리·위생·조리직 라운지',
      order: 85,
    ),

    // ========================================
    // 8. 기타 직렬
    // ========================================
    Lounge(
      id: 'postal_service',
      name: '우정직',
      emoji: '📮',
      shortName: '우정직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['postal_service'],
      memberCount: 50000,
      description: '우정직 공무원 라운지',
      order: 9,
    ),

    Lounge(
      id: 'researcher',
      name: '연구직',
      emoji: '🔬',
      shortName: '연구직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['researcher'],
      memberCount: 20000,
      description: '연구직 공무원 라운지',
      order: 10,
    ),

    // ========================================
    // 9. 신규 라운지 - 법조직 (신규)
    // ========================================
    Lounge(
      id: 'legal_profession',
      name: '법조직',
      emoji: '⚖️',
      shortName: '법조직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['judge', 'prosecutor'],
      memberCount: 5000,
      description: '판사·검사 전용 라운지',
      order: 11,
    ),

    // ========================================
    // 10. 신규 라운지 - 외교관 (신규)
    // ========================================
    Lounge(
      id: 'diplomat',
      name: '외교관',
      emoji: '🌐',
      shortName: '외교관',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'diplomat_5th',
        'diplomat_consular',
        'diplomat_3rd',
      ],
      memberCount: 4000,
      description: '외교관 전용 라운지',
      order: 12,
    ),

    // ========================================
    // 11. 신규 라운지 - 문화예술직 (신규)
    // ========================================
    Lounge(
      id: 'culture_arts',
      name: '문화예술직',
      emoji: '🎨',
      shortName: '문화예술직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: ['curator', 'cultural_heritage'],
      memberCount: 3000,
      description: '학예직·문화재직 라운지',
      order: 13,
    ),

    // ========================================
    // 12. 신규 라운지 - 과학기술 전문직 (신규)
    // ========================================
    Lounge(
      id: 'science_technology_specialized',
      name: '과학기술 전문직',
      emoji: '🔬',
      shortName: '과학기술 전문직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'meteorologist',
        'disaster_safety',
        'nursing_assistant',
        'health_care',
      ],
      memberCount: 7500,
      description: '기상·방재안전·간호조무·보건진료직 라운지',
      order: 14,
    ),

    // ========================================
    // 13. 신규 라운지 - 독립기관직 (신규)
    // ========================================
    Lounge(
      id: 'independent_agencies',
      name: '독립기관직',
      emoji: '🏛️',
      shortName: '독립기관직',
      type: LoungeType.specific,
      accessType: LoungeAccessType.careerOnly,
      requiredCareerIds: [
        'national_assembly',
        'constitutional_court',
        'election_commission',
        'audit_board',
        'human_rights_commission',
      ],
      memberCount: 6000,
      description: '국회·헌법재판소·선관위·감사원·인권위 라운지',
      order: 15,
    ),
  ];
}
