// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAGyvi8gqPUtdsv1PhDrlxCTNBgJ4_jyc',
    appId: '1:877880259407:android:8ac610256dcdac8c81cb3a',
    messagingSenderId: '877880259407',
    projectId: 'gong-mu-talk',
    authDomain: 'gong-mu-talk.firebaseapp.com',
    storageBucket: 'gong-mu-talk.firebasestorage.app',
    androidClientId:
        '877880259407-qvsk8dc1d4nsu3v301irq6eb1n41gbf2.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsgMuu8kf83jAiPH3lSB_yPCcoXI6U8wY',
    appId: '1:877880259407:ios:c36e32a3a649d45d81cb3a',
    messagingSenderId: '877880259407',
    projectId: 'gong-mu-talk',
    storageBucket: 'gong-mu-talk.firebasestorage.app',
    authDomain: 'gong-mu-talk.firebaseapp.com',
    iosClientId:
        '877880259407-bn8ij5nadelt71bs0globfna7ua2bisq.apps.googleusercontent.com',
    iosBundleId: 'com.hanisoft.gong-mu-talk',
  );
}
